#+TITLE: CLI Sauce
#+AUTHOR: Chef
#+DATE: <2025-02-17 Mon>

* TABLE OF CONTENTS :toc:
- [[#whats-cookin][What's cookin'?]]
  - [[#1-fortune-cookie-for-your-terminal][1. Fortune cookie for your terminal]]
  - [[#2-ff---a-simple-fetch][2. FF - a simple fetch]]
- [[#ingredients-needed][Ingredients needed]]
- [[#how-to-run-them][How to run them]]

* What's cookin'?
This repo serves up two simple scripts to make your terminal less boring
 
** 1. Fortune cookie for your terminal
Every time you open your terminal, BAM! A random quote pops up. Motivation? Wisdom? Just nonsense? Who knows!

** 2. FF - a simple fetch
A simple fetch script - nothing fancy. Shows:
- OS Name
- Kernel Version
- Uptime
- Shell
- Installed Packages
- CPU & Memory Usage

* Ingredients needed
#+begin_src bash
lolcat
figlet
bash (or zsh)
#+end_src

* How to run them
1. Clone this repo.
2. Add them to your =.bashrc= or =.zshrc= as suggested below
3. Open your terminal and bask in the glory.

#+begin_src bash
# add it to your .bashrc or .zshrc. This will autospawn it everytime you open the shell
$HOME/CLI-Sauce/forture_cookie.sh
#+end_src

#+begin_src bash
# add this as an alias in your .bashrc or .zshrc
alias ff='$HOME/CLI-Sauce/flex_flex.sh'

# Run alias to fetch
ff
#+end_src
